# Generated by Django 5.2.5 on 2025-08-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="speakers/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("place", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "speakers",
                    models.ManyToManyField(
                        blank=True, related_name="agenda_items", to="agenda.speaker"
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
