# Generated by Django 5.2.5 on 2025-08-27 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AgendaItem",
            new_name="Agenda",
        ),
        migrations.CreateModel(
            name="AgendaRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("attended", models.BooleanField(default=False)),
                ("attendance_marked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agenda_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="agenda.agenda",
                    ),
                ),
            ],
        ),
    ]
