# Generated by Django 5.2.5 on 2025-10-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_rename_agendaitem_agenda_agendaregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="speakers",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="agenda_items", to="agenda.speaker"
            ),
        ),
    ]
