# Generated by Django 5.2.5 on 2026-07-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0003_alter_agenda_speakers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agenda",
            name="speakers",
        ),
        migrations.AddField(
            model_name="agenda",
            name="capacity",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="agenda",
            name="event_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agenda",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agenda",
            name="requires_registration",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Speaker",
        ),
        migrations.AddField(
            model_name="agenda",
            name="speakers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
