# Generated by Django 5.2.5 on 2025-09-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="hiring_positions",
        ),
        migrations.RemoveField(
            model_name="company",
            name="status",
        ),
        migrations.AddField(
            model_name="company",
            name="field",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
