# Generated by Django 5.2.5 on 2025-10-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_user"),
        ("participants", "0012_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyParticipantLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_links",
                        to="companies.company",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_links",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company-Participant Link",
                "verbose_name_plural": "Company-Participant Links",
                "unique_together": {("company", "participant")},
            },
        ),
    ]
