# Generated by Django 5.2.5 on 2025-11-04 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_companyparticipantlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
