-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."status" AS ENUM('pending', 'succeeded', 'failed');--> statement-breakpoint
CREATE TABLE "django_migrations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_migrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"app" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"applied" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "django_content_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_content_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"app_label" varchar(100) NOT NULL,
	"model" varchar(100) NOT NULL,
	CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE("app_label","model")
);
--> statement-breakpoint
CREATE TABLE "auth_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"content_type_id" integer NOT NULL,
	"codename" varchar(100) NOT NULL,
	CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE("content_type_id","codename")
);
--> statement-breakpoint
CREATE TABLE "auth_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(150) NOT NULL,
	CONSTRAINT "auth_group_name_key" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "auth_group_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_id" integer NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE("group_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "accounts_customuser" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accounts_customuser_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"password" varchar(128) NOT NULL,
	"last_login" timestamp with time zone,
	"is_superuser" boolean NOT NULL,
	"username" varchar(150) NOT NULL,
	"first_name" varchar(150) NOT NULL,
	"last_name" varchar(150) NOT NULL,
	"is_staff" boolean NOT NULL,
	"is_active" boolean NOT NULL,
	"date_joined" timestamp with time zone NOT NULL,
	"email" varchar(254) NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"role" varchar(2) NOT NULL,
	"password_set" boolean NOT NULL,
	CONSTRAINT "accounts_customuser_username_key" UNIQUE("username"),
	CONSTRAINT "accounts_customuser_email_key" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "accounts_customuser_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accounts_customuser_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"customuser_id" bigint NOT NULL,
	"group_id" integer NOT NULL,
	CONSTRAINT "accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq" UNIQUE("customuser_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "agenda_agenda_speakers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agenda_agendaitem_speakers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"agenda_id" bigint NOT NULL,
	"speaker_id" bigint NOT NULL,
	CONSTRAINT "agenda_agendaitem_speake_agendaitem_id_speaker_id_9166fdcb_uniq" UNIQUE("agenda_id","speaker_id")
);
--> statement-breakpoint
CREATE TABLE "agenda_agenda" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agenda_agendaitem_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"start_time" timestamp with time zone NOT NULL,
	"end_time" timestamp with time zone NOT NULL,
	"place" varchar(255) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agenda_agendaregistration" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agenda_agendaregistration_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"registered_at" timestamp with time zone NOT NULL,
	"attended" boolean NOT NULL,
	"attendance_marked_at" timestamp with time zone,
	"agenda_item_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "participants_participant" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "participants_participant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"participant_type" varchar(2) NOT NULL,
	"status" varchar(10) NOT NULL,
	"registered_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"approved_by_id" bigint,
	"linkedin_url" varchar(200) NOT NULL,
	"payment_status" varchar(50) NOT NULL,
	"approved_at" timestamp with time zone,
	"cv_file" varchar(500),
	"graduation_year" varchar(50) NOT NULL,
	"rejection_reason" text NOT NULL,
	"university" varchar(255) NOT NULL,
	"user_id" bigint,
	"academic_level" varchar(255) NOT NULL,
	"academic_level_other" varchar(255) NOT NULL,
	"additional_comments" text NOT NULL,
	"attended_before" boolean NOT NULL,
	"benefit_from_event" text NOT NULL,
	"field_of_study" varchar(255) NOT NULL,
	"field_of_study_other" varchar(255) NOT NULL,
	"graduation_year_other" varchar(50) NOT NULL,
	"heard_about" varchar(255) NOT NULL,
	"heard_about_other" varchar(255) NOT NULL,
	"personal_description" text NOT NULL,
	"perspective_gala" text NOT NULL,
	"plans_next_year" text NOT NULL,
	"university_other" varchar(255) NOT NULL,
	"phone" varchar(20) NOT NULL,
	"email" varchar(254),
	"first_name" varchar(150),
	"last_name" varchar(150),
	CONSTRAINT "participants_participant_user_id_key" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "django_session" (
	"session_key" varchar(40) PRIMARY KEY NOT NULL,
	"session_data" text NOT NULL,
	"expire_date" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tickets_ticket" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tickets_ticket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"serial_number" varchar(20) NOT NULL,
	"status" varchar(20) NOT NULL,
	"issued_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone,
	"checked_in_at" timestamp with time zone,
	"email_sent" boolean NOT NULL,
	"email_sent_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"checked_in_by_id" bigint,
	"participant_id" bigint,
	CONSTRAINT "tickets_ticket_ticket_number_key" UNIQUE("serial_number"),
	CONSTRAINT "tickets_ticket_participant_id_key" UNIQUE("participant_id")
);
--> statement-breakpoint
CREATE TABLE "tickets_ticketscan" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tickets_ticketscan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"scan_datetime" timestamp with time zone NOT NULL,
	"scan_location" varchar(100),
	"scan_result" varchar(20) NOT NULL,
	"scanned_by_id" bigint NOT NULL,
	"ticket_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "token_blacklist_outstandingtoken" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "token_blacklist_outstandingtoken_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token" text NOT NULL,
	"created_at" timestamp with time zone,
	"expires_at" timestamp with time zone NOT NULL,
	"user_id" bigint,
	"jti" varchar(255) NOT NULL,
	CONSTRAINT "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq" UNIQUE("jti")
);
--> statement-breakpoint
CREATE TABLE "agenda_speaker" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agenda_speaker_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"bio" text NOT NULL,
	"company_name" varchar(255) NOT NULL,
	"photo" varchar(100)
);
--> statement-breakpoint
CREATE TABLE "companies_company" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "companies_company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"description" text,
	"email" varchar(254) NOT NULL,
	"website" varchar(200),
	"contact_person" varchar(100),
	"phone" varchar(20),
	"address" text,
	"logo" varchar(100),
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"field" varchar(100),
	"user_id" bigint,
	CONSTRAINT "companies_company_user_id_key" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "companies_companyparticipantlink" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "companies_companyparticipantlink_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone NOT NULL,
	"company_id" bigint NOT NULL,
	"participant_id" bigint NOT NULL,
	CONSTRAINT "companies_companypartici_company_id_participant_i_22c1511b_uniq" UNIQUE("company_id","participant_id")
);
--> statement-breakpoint
CREATE TABLE "notifications_emaillog" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_emaillog_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"recipient_email" varchar(254) NOT NULL,
	"recipient_name" varchar(100),
	"subject" varchar(200) NOT NULL,
	"body_html" text,
	"body_text" text,
	"status" varchar(20) NOT NULL,
	"sent_at" timestamp with time zone,
	"delivery_status" text,
	"error_message" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"participant_id" bigint,
	"sent_by_id" bigint,
	"template_used_id" bigint
);
--> statement-breakpoint
CREATE TABLE "notifications_emailtemplate" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_emailtemplate_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"template_type" varchar(30) NOT NULL,
	"subject" varchar(200) NOT NULL,
	"body_html" text NOT NULL,
	"body_text" text NOT NULL,
	"is_active" boolean NOT NULL,
	"available_variables" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "notifications_emailtemplate_template_type_key" UNIQUE("template_type")
);
--> statement-breakpoint
CREATE TABLE "notifications_notification" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"notification_type" varchar(30) NOT NULL,
	"title" varchar(200) NOT NULL,
	"message" text NOT NULL,
	"is_read" boolean NOT NULL,
	"read_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"participant_id" bigint,
	"recipient_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "participants_feedback" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "participants_feedback_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"feedback" text NOT NULL,
	"submitted_at" timestamp with time zone NOT NULL,
	"participant_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" uuid PRIMARY KEY NOT NULL,
	"participant_id" integer NOT NULL,
	"amount" bigint NOT NULL,
	"status" "status" NOT NULL,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "accounts_customuser_user_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accounts_customuser_user_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"customuser_id" bigint NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "accounts_customuser_user_customuser_id_permission_9632a709_uniq" UNIQUE("customuser_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "django_admin_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_admin_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action_time" timestamp with time zone NOT NULL,
	"object_id" text,
	"object_repr" varchar(200) NOT NULL,
	"action_flag" smallint NOT NULL,
	"change_message" text NOT NULL,
	"content_type_id" integer,
	"user_id" bigint NOT NULL,
	CONSTRAINT "django_admin_log_action_flag_check" CHECK (action_flag >= 0)
);
--> statement-breakpoint
CREATE TABLE "token_blacklist_blacklistedtoken" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "token_blacklist_blacklistedtoken_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"blacklisted_at" timestamp with time zone NOT NULL,
	"token_id" bigint NOT NULL,
	CONSTRAINT "token_blacklist_blacklistedtoken_token_id_key" UNIQUE("token_id")
);
--> statement-breakpoint
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts_customuser_groups" ADD CONSTRAINT "accounts_customuser__customuser_id_bc55088e_fk_accounts_" FOREIGN KEY ("customuser_id") REFERENCES "public"."accounts_customuser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts_customuser_groups" ADD CONSTRAINT "accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agenda_agenda_speakers" ADD CONSTRAINT "agenda_agendaitem_sp_speaker_id_2d5972dd_fk_agenda_sp" FOREIGN KEY ("speaker_id") REFERENCES "public"."agenda_speaker"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agenda_agenda_speakers" ADD CONSTRAINT "agenda_agenda_speakers_agenda_id_7edf93b6_fk_agenda_agenda_id" FOREIGN KEY ("agenda_id") REFERENCES "public"."agenda_agenda"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agenda_agendaregistration" ADD CONSTRAINT "agenda_agendaregistr_agenda_item_id_062394da_fk_agenda_ag" FOREIGN KEY ("agenda_item_id") REFERENCES "public"."agenda_agenda"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participants_participant" ADD CONSTRAINT "participants_partici_approved_by_id_bdf59a9e_fk_accounts_" FOREIGN KEY ("approved_by_id") REFERENCES "public"."accounts_customuser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participants_participant" ADD CONSTRAINT "participants_partici_user_id_a3da47e5_fk_accounts_" FOREIGN KEY ("user_id") REFERENCES "public"."accounts_customuser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets_ticket" ADD CONSTRAINT "tickets_ticket_checked_in_by_id_f7f60f19_fk_accounts_" FOREIGN KEY ("checked_in_by_id") REFERENCES "public"."accounts_customuser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets_ticket" ADD CONSTRAINT "tickets_ticket_participant_id_685cb502_fk_participa" FOREIGN KEY ("participant_id") REFERENCES "public"."participants_participant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets_ticketscan" ADD CONSTRAINT "tickets_ticketscan_scanned_by_id_0657ee6e_fk_accounts_" FOREIGN KEY ("scanned_by_id") REFERENCES "public"."accounts_customuser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets_ticketscan" ADD CONSTRAINT "tickets_ticketscan_ticket_id_0df45168_fk_tickets_ticket_id" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets_ticket"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_accounts_" FOREIGN KEY ("user_id") REFERENCES "public"."accounts_customuser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "companies_company" ADD CONSTRAINT "companies_company_user_id_175c2d31_fk_accounts_customuser_id" FOREIGN KEY ("user_id") REFERENCES "public"."accounts_customuser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "companies_companyparticipantlink" ADD CONSTRAINT "companies_companypar_company_id_bc7e134a_fk_companies" FOREIGN KEY ("company_id") REFERENCES "public"."companies_company"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "companies_companyparticipantlink" ADD CONSTRAINT "companies_companypar_participant_id_4716043d_fk_participa" FOREIGN KEY ("participant_id") REFERENCES "public"."participants_participant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications_emaillog" ADD CONSTRAINT "notifications_emaill_participant_id_f85aedc1_fk_participa" FOREIGN KEY ("participant_id") REFERENCES "public"."participants_participant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications_emaillog" ADD CONSTRAINT "notifications_emaill_sent_by_id_31a67c4a_fk_accounts_" FOREIGN KEY ("sent_by_id") REFERENCES "public"."accounts_customuser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications_emaillog" ADD CONSTRAINT "notifications_emaill_template_used_id_78046de5_fk_notificat" FOREIGN KEY ("template_used_id") REFERENCES "public"."notifications_emailtemplate"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications_notification" ADD CONSTRAINT "notifications_notifi_participant_id_b9479876_fk_participa" FOREIGN KEY ("participant_id") REFERENCES "public"."participants_participant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications_notification" ADD CONSTRAINT "notifications_notifi_recipient_id_d055f3f0_fk_accounts_" FOREIGN KEY ("recipient_id") REFERENCES "public"."accounts_customuser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participants_feedback" ADD CONSTRAINT "participants_feedbac_participant_id_3416e3fe_fk_participa" FOREIGN KEY ("participant_id") REFERENCES "public"."participants_participant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts_customuser_user_permissions" ADD CONSTRAINT "accounts_customuser__customuser_id_0deaefae_fk_accounts_" FOREIGN KEY ("customuser_id") REFERENCES "public"."accounts_customuser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts_customuser_user_permissions" ADD CONSTRAINT "accounts_customuser__permission_id_aea3d0e5_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_accounts_customuser_id" FOREIGN KEY ("user_id") REFERENCES "public"."accounts_customuser"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "token_blacklist_blacklistedtoken" ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk" FOREIGN KEY ("token_id") REFERENCES "public"."token_blacklist_outstandingtoken"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" USING btree ("name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "accounts_customuser_email_4fd8e7ce_like" ON "accounts_customuser" USING btree ("email" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "accounts_customuser_username_722f3555_like" ON "accounts_customuser" USING btree ("username" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "accounts_customuser_groups_customuser_id_bc55088e" ON "accounts_customuser_groups" USING btree ("customuser_id" int8_ops);--> statement-breakpoint
CREATE INDEX "accounts_customuser_groups_group_id_86ba5f9e" ON "accounts_customuser_groups" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "agenda_agendaitem_speakers_agendaitem_id_8284f94f" ON "agenda_agenda_speakers" USING btree ("agenda_id" int8_ops);--> statement-breakpoint
CREATE INDEX "agenda_agendaitem_speakers_speaker_id_2d5972dd" ON "agenda_agenda_speakers" USING btree ("speaker_id" int8_ops);--> statement-breakpoint
CREATE INDEX "agenda_agendaregistration_agenda_item_id_062394da" ON "agenda_agendaregistration" USING btree ("agenda_item_id" int8_ops);--> statement-breakpoint
CREATE INDEX "participants_participant_approved_by_id_bdf59a9e" ON "participants_participant" USING btree ("approved_by_id" int8_ops);--> statement-breakpoint
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" USING btree ("expire_date" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" USING btree ("session_key" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "tickets_ticket_checked_in_by_id_f7f60f19" ON "tickets_ticket" USING btree ("checked_in_by_id" int8_ops);--> statement-breakpoint
CREATE INDEX "tickets_ticket_ticket_number_d9b1511a_like" ON "tickets_ticket" USING btree ("serial_number" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "tickets_ticketscan_scanned_by_id_0657ee6e" ON "tickets_ticketscan" USING btree ("scanned_by_id" int8_ops);--> statement-breakpoint
CREATE INDEX "tickets_ticketscan_ticket_id_0df45168" ON "tickets_ticketscan" USING btree ("ticket_id" int8_ops);--> statement-breakpoint
CREATE INDEX "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like" ON "token_blacklist_outstandingtoken" USING btree ("jti" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "token_blacklist_outstandingtoken" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "companies_companyparticipantlink_company_id_bc7e134a" ON "companies_companyparticipantlink" USING btree ("company_id" int8_ops);--> statement-breakpoint
CREATE INDEX "companies_companyparticipantlink_participant_id_4716043d" ON "companies_companyparticipantlink" USING btree ("participant_id" int8_ops);--> statement-breakpoint
CREATE INDEX "notifications_emaillog_participant_id_f85aedc1" ON "notifications_emaillog" USING btree ("participant_id" int8_ops);--> statement-breakpoint
CREATE INDEX "notifications_emaillog_sent_by_id_31a67c4a" ON "notifications_emaillog" USING btree ("sent_by_id" int8_ops);--> statement-breakpoint
CREATE INDEX "notifications_emaillog_template_used_id_78046de5" ON "notifications_emaillog" USING btree ("template_used_id" int8_ops);--> statement-breakpoint
CREATE INDEX "notifications_emailtemplate_template_type_1c3f0c6b_like" ON "notifications_emailtemplate" USING btree ("template_type" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "notifications_notification_participant_id_b9479876" ON "notifications_notification" USING btree ("participant_id" int8_ops);--> statement-breakpoint
CREATE INDEX "notifications_notification_recipient_id_d055f3f0" ON "notifications_notification" USING btree ("recipient_id" int8_ops);--> statement-breakpoint
CREATE INDEX "participants_feedback_participant_id_3416e3fe" ON "participants_feedback" USING btree ("participant_id" int8_ops);--> statement-breakpoint
CREATE INDEX "accounts_customuser_user_permissions_customuser_id_0deaefae" ON "accounts_customuser_user_permissions" USING btree ("customuser_id" int8_ops);--> statement-breakpoint
CREATE INDEX "accounts_customuser_user_permissions_permission_id_aea3d0e5" ON "accounts_customuser_user_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" USING btree ("user_id" int8_ops);
*/