# Generated by Django 5.2.5 on 2025-09-01 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="can_approve_participants",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="can_manage_agenda",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="can_manage_companies",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="can_manage_tickets",
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("HR", "HR Admin"), ("P", "Participant")],
                default="P",
                max_length=2,
            ),
        ),
    ]
