# Generated by Django 5.2.5 on 2025-09-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="department",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="employee_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone",
        ),
    ]
