# Generated by Django 5.2.5 on 2025-10-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_set",
            field=models.BooleanField(default=False),
        ),
    ]
