# Generated by Django 5.2.5 on 2025-10-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_password_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("HR", "HR Admin"), ("P", "Participant"), ("C", "Company")],
                default="P",
                max_length=2,
            ),
        ),
    ]
