# Generated by Django 5.2.5 on 2025-08-24 15:32

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        default=tickets.models.generate_serial_number,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("qr_code_data", models.TextField()),
                (
                    "qr_code_image",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                ("security_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("cancelled", "Cancelled"),
                            ("checked_in", "Checked In"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "table_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("special_access", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_in_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "scan_result",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("already_used", "Already Used"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "scanned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Scan",
                "verbose_name_plural": "Ticket Scans",
                "ordering": ["-scan_datetime"],
            },
        ),
    ]
