# Generated by Django 5.2.5 on 2025-09-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="ticket_number",
            new_name="serial_number",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="qr_code_data",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="qr_code_image",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="security_hash",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="special_access",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="table_number",
        ),
    ]
