# Generated by Django 5.2.5 on 2025-09-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_rename_ticket_number_ticket_serial_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketscan",
            name="notes",
        ),
    ]
