# Generated by Django 5.2.5 on 2025-10-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0008_delete_company"),
        ("tickets", "0003_remove_ticketscan_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="participant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket",
                to="participants.participant",
            ),
        ),
    ]
