# Generated by Django 5.2.5 on 2025-11-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_alter_ticket_participant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="used_at",
            new_name="assigned_at",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("assigned", "Assigned"),
                    ("cancelled", "Cancelled"),
                    ("checked_in", "Checked In"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticketscan",
            name="scan_result",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("invalid", "Invalid"),
                    ("already_assigned", "Already Assigned"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
