# Generated by Django 5.2.5 on 2025-08-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="company",
        ),
        migrations.AddField(
            model_name="participant",
            name="linked_in",
            field=models.URLField(blank=True),
        ),
    ]
