# Generated by Django 5.2.5 on 2025-08-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0002_remove_participant_company_participant_linked_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("vip", "VIP"),
                    ("regular", "Regular"),
                    ("student", "Student"),
                ],
                default="regular",
                max_length=100,
            ),
        ),
    ]
