# Generated by Django 5.2.5 on 2025-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0003_participant_payment_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="linked_in",
            new_name="linkedin_url",
        ),
        migrations.AddField(
            model_name="participant",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="cv_file",
            field=models.FileField(blank=True, null=True, upload_to="media/cvs/"),
        ),
        migrations.AddField(
            model_name="participant",
            name="graduation_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="university",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
