# Generated by Django 5.2.5 on 2025-09-01 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0004_rename_linked_in_participant_linkedin_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="email",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="cv_file",
            field=models.FileField(blank=True, null=True, upload_to="cvs/"),
        ),
    ]
