# Generated by Django 5.2.5 on 2025-09-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0005_remove_participant_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="registration_type",
        ),
    ]
