# Generated by Django 5.2.5 on 2025-09-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0006_remove_participant_registration_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
