# Generated by Django 5.2.5 on 2025-09-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0007_delete_ticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
    ]
