# Generated by Django 5.2.5 on 2025-10-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0008_delete_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="academic_level",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="participant",
            name="academic_level_other",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="participant",
            name="additional_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="attended_before",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participant",
            name="benefit_from_event",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="participant",
            name="field_of_study_other",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="participant",
            name="graduation_year_other",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="participant",
            name="heard_about",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="participant",
            name="heard_about_other",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="participant",
            name="personal_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="perspective_gala",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="plans_next_year",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="university_other",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="participant",
            name="graduation_year",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="participant",
            name="participant_type",
            field=models.CharField(
                choices=[("ST", "Student"), ("G", "Guest")], default="G", max_length=2
            ),
        ),
    ]
