# Generated by Django 5.2.5 on 2025-10-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0009_participant_academic_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
