# Generated by Django 5.2.5 on 2025-10-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0010_participant_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="participant_type",
            field=models.CharField(
                choices=[("ST", "Student"), ("G", "Guest")], default="ST", max_length=2
            ),
        ),
    ]
