# Generated by Django 5.2.5 on 2025-10-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0012_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="job_title",
        ),
    ]
