# Generated by Django 5.2.5 on 2025-10-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0013_remove_participant_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="cv_file",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
