# Generated by Django 5.2.5 on 2025-10-30 15:36

import django.db.models.deletion
import participants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0014_alter_participant_cv_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="id",
            field=models.BigIntegerField(
                default=participants.models.generate_participant_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="ParticipantParticipantLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_links",
                        to="participants.participant",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_by_current_participant",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant-Participant Link",
                "verbose_name_plural": "Participant-Participant Links",
                "unique_together": {("current_participant", "participant")},
            },
        ),
    ]
