# Generated by Django 5.2.5 on 2025-11-01 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0015_alter_participant_id_participantparticipantlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="cv_file",
        ),
        migrations.CreateModel(
            name="ParticipantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("cloudinary_public_id", models.CharField(max_length=255, unique=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
