# Generated by Django 5.2.5 on 2025-09-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaillog",
            name="clicked_at",
        ),
        migrations.RemoveField(
            model_name="emaillog",
            name="opened_at",
        ),
    ]
