# Generated by Django 5.2.5 on 2025-10-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_remove_emaillog_clicked_at_remove_emaillog_opened_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("registration_confirmation", "Registration Confirmation"),
                    ("approval_notification", "Approval Notification"),
                    ("rejection_notification", "Rejection Notification"),
                    ("payment_reminder", "Payment Reminder"),
                    ("ticket_delivery", "Ticket Delivery"),
                    ("event_reminder", "Event Reminder"),
                    ("event_update", "Event Update"),
                    ("payment_confirmation", "Payment Confirmation"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
